[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.21"
optimizer = true 
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
bit_layer_testnet = "${BIT_LAYER_TESTNET_RPC_URL}"
bit_layer = "${BIT_LAYER_RPC_URL}"
merlin = "${MERLIN_RPC_URL}"
bsquared = "${BSQUARED_RPC_URL}"
sepolia = "${SPEOLIA_RPC_URL}"
ai_layer = "${AILAYER_RPC_URL}"

# [etherscan]
# bit_layer_testnet = { key = "${ETHERSCAN_API_KEY}", chain = "200810", url = "https://testnet-scan.bitlayer.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
